FORMAT: 1A
HOST: http://ec2-52-66-60-159.ap-south-1.compute.amazonaws.com/car-pool/

# car-pool

Car pool is an API for a car pooling webapp.

## Listings Collection [/listings/{listing_id}]

### List All Listings [GET]

+ Parameters
    + listing_id (number, optional) - ID of the Listing in the form of an integer

+ Response 200 (application/json)

             {
                "id": 2,
                "address": {
                  "id": 2,
                  "latitude": 1.121,
                  "longitude": -11.121,
                  "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                },
                "source": {
                  "id": 2,
                  "address": {
                      "id": 2,
                      "latitude": 1.121,
                      "longitude": -11.121
                      "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                  },
                  "name": "practo"
                },
                "user": {
                  "id": 6,
                  "name": "Poorna Teja",
                  "email": "poorna@practo.com",
                  "phone": "9965678867"
                },
                "vehicle": {
                  "id": 2,
                  "capacity": 2,
                  "model": "BMW",
                  "numberPlate": "KA22113390",
                  "user": {
                    "id": 6,
                    "name": "Poorna Teja",
                    "email": "poorna@practo.com",
                    "phone": "65678867"
                  }
                },
                "departureTime": 147160196000,
                "seatsAvailable": 2
              }
        

### Create a New Listing [POST]

+ Request (application/json)
        
          {
                "address": {
                      "id": 1
                },
                "source": {
                      "id": 2
                },
                "user": {
                      "id": 1
                },
                "vehicle": {
                      "id": 1
                },
                "departureTime": 147150196100,
                "seatsAvailable": 4
          }

+ Response 201 (application/json)

    + Headers

            Location: /listings/6

    + Body

            {
                        "id": 6,
                        "address": {
                                    "id": 1,
                                    "latitude": null,
                                    "longitude": null,
                                    "formatted_address": null
                        },
                        "source": {
                                    "id": 2,
                                    "address": null,
                                    "name": null
                        },
                        "user": {
                                    "id": 1,
                                    "name": null,
                                    "email": null,
                                    "phone": null
                        },
                        "vehicle": {
                                    "id": 1,
                                    "capacity": 0,
                                    "model": null,
                                    "numberPlate": null,
                                    "user": null
                        },
                        "departureTime": 147150196100,
                        "seatsAvailable": 4
            }


### Update a Listing [PUT]

+ Parameters
    + listing_id (number) - ID of the Listing in the form of an integer
    
+ Request (application/json)

          {
                "address": {
                      "id": 1
                },
                "source": {
                      "id": 1
                },
                "user": {
                      "id": 1
                },
                "vehicle": {
                      "id": 2
                },
                "departureTime": 157150196100,
                "seatsAvailable": 2
          }

+ Response 200 (application/json)

    + Headers

            Location: /listings/2

    + Body

            {
                "id": 1,
                "address": {
                  "id": 2,
                  "latitude": 1.121,
                  "longitude": -11.121,
                  "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                },
                "source": {
                  "id": 1,
                  "address": {
                      "id": 2,
                      "latitude": 1.121,
                      "longitude": -11.121,
                      "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                  },
                  "name": "practo"
                },
                "user": {
                  "id": 1,
                  "name": "Poorna Teja",
                  "email": "poorna@practo.com",
                  "phone": "9965678867"
                },
                "vehicle": {
                  "id": 2,
                  "capacity": 2,
                  "model": "BMW",
                  "numberPlate": "KA22113390",
                  "user": {
                    "id": 6,
                    "name": "Poorna Teja",
                    "email": "poorna@practo.com",
                    "phone": "65678867"
                  }
                },
                "departureTime": 157160196000,
                "seatsAvailable": 2
            }

### Delete a Listing [DELETE]

+ Response 204



## Bookings Collection [/users/{user_id}/bookings/{booking_id}]

### List All Bookings [GET]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + booking_id (number, optional) - ID of the Booking in the form of an integer
    
+ Response 200 (application/json)

        
              {
                "id": 1,
                "listing": {
                  "id": 2,
                  "address": {
                    "id": 2,
                    "latitude": 1.121,
                    "longitude": -11.121,
                    "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                  },
                  "source": {
                    "id": 2,
                    "address": {
                      "id": 2,
                      "latitude": 1.121,
                      "longitude": -11.121,
                      "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                    },
                    "name": "practo"
                  },
                  "user": {
                    "id": 6,
                    "name": "Poorna Teja",
                    "email": "poorna@practo.com",
                    "phone": "65678867"
                  },
                  "vehicle": {
                    "id": 2,
                    "capacity": 2,
                    "model": "qwer",
                    "numberPlate": "asdf",
                    "user": {
                      "id": 6,
                      "name": "Poorna Teja",
                      "email": "poorna@practo.com",
                      "phone": "65678867"
                    }
                  },
                  "departureTime": 147160196000,
                  "seatsAvailable": 2
                },
                "user": {
                  "id": 1,
                  "name": "Prashant",
                  "email": "prashant@practo.com",
                  "phone": "9565067200"
                }
              }
 
        

### Create a New Booking [POST]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

+ Request (application/json)

            {
                "listing": {
                    "id": 5
                }
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/2/bookings/4

    + Body

            {
                  "id": 4,
                  "listing": {
                    "id": 2,
                    "address": null,
                    "source": null,
                    "user": null,
                    "vehicle": null,
                    "departureTime": null,
                    "seatsAvailable": 0
                  },
                  "user": {
                    "id": 5,
                    "name": null,
                    "email": null,
                    "phone": null
                  }
            }


### Update a Booking [PUT]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + booking_id (number, optional) - ID of the Booking in the form of an integer
    
+ Request (application/json)

            {
                "listing": {
                    "id": 1
                }
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/2/bookings/4

    + Body

            {
                  "id": 3,
                  "listing": {
                    "id": 2,
                    "address": {
                      "id": 2,
                      "latitude": 1.121,
                      "longitude": -11.121,
                      "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                    },
                    "source": {
                      "id": 2,
                      "address": {
                        "id": 2,
                        "latitude": 1.121,
                        "longitude": -11.121,
                        "formatted_address": "12th Cross, 11th Main, JP Nagar Phase 5, Bangalore"
                      },
                      "name": "practo"
                    },
                    "user": {
                      "id": 6,
                      "name": "Poorna Teja",
                      "email": "poorna@practo.com",
                      "phone": "65678867"
                    },
                    "vehicle": {
                      "id": 2,
                      "capacity": 2,
                      "model": "qwer",
                      "numberPlate": "asdf",
                      "user": {
                        "id": 6,
                        "name": "Poorna Teja",
                        "email": "poorna@practo.com",
                        "phone": "65678867"
                      }
                    },
                    "departureTime": 147160196000,
                    "seatsAvailable": 2
                  },
                  "user": {
                    "id": 1,
                    "name": "Prashant",
                    "email": "prashant@practo.com",
                    "phone": "9565067200"
                  }
            }

### Delete a Booking [DELETE]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + booking_id (number, optional) - ID of the Booking in the form of an integer

+ Response 204

## Users Collection [/users/{user_id}]

### List All Users [GET]

+ Parameters
    + user_id (number, optional) - ID of the User in the form of an integer

+ Response 200 (application/json)

        
              {
                "id": 1,
                "name": "Prashant",
                "email": "prashant@practo.com",
                "phone": "9565067200"
              }
        

### Create a New User [POST]

+ Request (application/json)

            {
                "email": "abdul@practo.com",
                "name": "abdul",
                "phone": "9901223334"
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/9

    + Body

            {
              "id": 9,
              "name": "abdul",
              "email": "abdul@practo.com",
              "phone": "9901223334"
            }


### Update a User [PUT]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    
+ Request (application/json)

            {
                "email": "abdul@practo.com",
                "name": "abdul",
                "phone": "9999988888"
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/9

    + Body

            {
              "id": 9,
              "name": "abdul",
              "email": "abdul@practo.com",
              "phone": "9999988888"
            }

### Delete a User [DELETE]

+ Response 204



## Vehicles Collection [/users/{user_id}/vehicles/{vehicle_id}]

### List All Vehicles [GET]


+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + vehicle_id (number, optional) - ID of the Vehicle in the form of an integer
    

+ Response 200 (application/json)


              {
                "id": 1,
                "capacity": 4,
                "model": "BMW",
                "numberPlate": "dsfsdfsdfsd",
                "user": {
                  "id": 1,
                  "name": "Prashant",
                  "email": "prashant@practo.com",
                  "phone": "9565067200"
                }
              }
        

### Create a New Vehicle [POST]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

+ Request (application/json)
            
            {
                "capacity": 3,
                "model": "qaz",
                "numberPlate": "xsw"
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/5/vehicles/6

    + Body

            {
                  "id": 6,
                  "capacity": 3,
                  "model": "qaz",
                  "numberPlate": "xsw",
                  "user": {
                    "id": 5,
                    "name": null,
                    "email": null,
                    "phone": null
                  }
            }


### Update a Vehicle [PUT]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + vehicle_id (number, optional) - ID of the Vehicle in the form of an integer
    
+ Request (application/json)

            {
              "id": 6,
              "capacity": 3,
              "model": "qaz",
              "numberPlate": "xsw",
              "user": {
                "id": 5,
                "name": null,
                "email": null,
                "phone": null
              }
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/5/vehicles/6

    + Body

            {
                  "id": 6,
                  "capacity": 3,
                  "model": "qazedc",
                  "numberPlate": "xsw",
                  "user": {
                    "id": 5,
                    "name": "Chetan",
                    "email": "chetan@practo.com",
                    "phone": "1231231231"
                  }
            }

### Delete a Vehicle [DELETE]

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + vehicle_id (number, optional) - ID of the Vehicle in the form of an integer

+ Response 204