-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 11:04:27 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car_pool
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `car_pool` ;

-- -----------------------------------------------------
-- Schema car_pool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_pool` DEFAULT CHARACTER SET utf8 ;
USE `car_pool` ;

-- -----------------------------------------------------
-- Table `car_pool`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`users` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`vehicles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`vehicles` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`vehicles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `capacity` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `number_plate` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id_vehicles`
    FOREIGN KEY (`user_id`)
    REFERENCES `car_pool`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`addresses` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`addresses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `street_number` VARCHAR(20) NULL,
  `route` VARCHAR(45) NULL,
  `neighborhood` VARCHAR(45) NULL,
  `sublocality` VARCHAR(45) NULL,
  `administrative_area_level_2` VARCHAR(45) NULL,
  `administrative_area_level_1` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `postal_code` VARCHAR(20) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`sources` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`sources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `address_id_idx` (`address_id` ASC),
  CONSTRAINT `address_id_sources`
    FOREIGN KEY (`address_id`)
    REFERENCES `car_pool`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`listings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`listings` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`listings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `car_id` INT NOT NULL,
  `departure_time` TIMESTAMP NOT NULL,
  `source_id` INT NOT NULL,
  `destination_address_id` INT NOT NULL,
  `seats_available` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `car_id_idx` (`car_id` ASC),
  INDEX `source_id_idx` (`source_id` ASC),
  INDEX `destination_address_id_idx` (`destination_address_id` ASC),
  CONSTRAINT `user_id_listings`
    FOREIGN KEY (`user_id`)
    REFERENCES `car_pool`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `car_id_listings`
    FOREIGN KEY (`car_id`)
    REFERENCES `car_pool`.`vehicles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `source_id_listings`
    FOREIGN KEY (`source_id`)
    REFERENCES `car_pool`.`sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `destination_address_id_listings`
    FOREIGN KEY (`destination_address_id`)
    REFERENCES `car_pool`.`addresses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_pool`.`bookings` ;

CREATE TABLE IF NOT EXISTS `car_pool`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `listing_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  INDEX `listing_id_idx` (`listing_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `user_id_bookings`
    FOREIGN KEY (`user_id`)
    REFERENCES `car_pool`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `listing_id_bookings`
    FOREIGN KEY (`listing_id`)
    REFERENCES `car_pool`.`listings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
